import React from 'react';
import { Spinner } from './Spinner';

interface MediaDisplayProps {
  generatedImage: string | null;
  generatedVideo: string | null;
  isLoading: boolean;
  loadingMessage: string;
  initialMessage: string;
}

export const MediaDisplay: React.FC<MediaDisplayProps> = ({
  generatedImage,
  generatedVideo,
  isLoading,
  loadingMessage,
  initialMessage,
}) => {
  const hasMedia = generatedImage || generatedVideo;

  return (
    <div className="bg-slate-900/50 backdrop-blur-xl border border-slate-700/50 rounded-2xl p-6 shadow-2xl flex flex-col items-center justify-center aspect-square min-h-[75vh]">
      {isLoading && (
        <div className="text-center">
          <Spinner />
          <p className="mt-4 text-lg text-slate-300 animate-pulse">{loadingMessage}</p>
        </div>
      )}
      {!isLoading && hasMedia && (
        <div className="w-full h-full flex flex-col gap-4">
            {generatedImage && (
              <>
                <div className="flex-grow w-full h-full min-h-0 rounded-xl overflow-hidden border border-slate-700/50">
                    <img
                        src={generatedImage}
                        alt="Generated by AI"
                        className="w-full h-full object-contain"
                    />
                </div>
                <a
                    href={generatedImage}
                    download="ai-generated-image.png"
                    className="w-full block bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded-lg text-center transition-colors"
                >
                    Download Image
                </a>
              </>
            )}
            {generatedVideo && (
                 <>
                    <div className="flex-grow w-full h-full min-h-0 rounded-xl overflow-hidden border border-slate-700/50">
                        <video
                            src={generatedVideo}
                            controls
                            autoPlay
                            loop
                            className="w-full h-full object-contain bg-black"
                        />
                    </div>
                    <a
                        href={generatedVideo}
                        download="ai-generated-video.mp4"
                        className="w-full block bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded-lg text-center transition-colors"
                    >
                        Download Video
                    </a>
                </>
            )}
        </div>
      )}
      {!isLoading && !hasMedia && (
        <div className="text-center text-slate-600">
            <svg xmlns="http://www.w3.org/2000/svg" className="mx-auto h-20 w-20" width="44" height="44" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" fill="none" strokeLinecap="round" strokeLinejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                <path d="M15 8h.01" />
                <path d="M11.5 21h-5.5a3 3 0 0 1 -3 -3v-12a3 3 0 0 1 3 -3h12a3 3 0 0 1 3 3v5.5" />
                <path d="M3 16l5 -5c.928 -.893 2.072 -.893 3 0l2 2" />
                <path d="M19 16l-2 -2c-.928 -.893 -2.072 -.893 -3 0l-2 2" />
                <path d="M14 14l1 -1" />
                <path d="M19 22v-6" />
                <path d="M22 19l-3 -3l-3 3" />
            </svg>
            <p className="mt-2 text-lg">{initialMessage}</p>
        </div>
      )}
    </div>
  );
};